backend:
  name: github
  repo: joaojusto/jose-gomes-landing-page

media_folder: "media/"

collections:
  - name: "events"
    label: "Eventos"
    folder: "src/data/events"
    create: true
    slug: "{{uuid}}"
    fields:
      - { name: "location", label: "Localização", widget: "string" }
      - { name: "title", label: "Nome", widget: "string" }
      - { name: "description", label: "Descrição", widget: "text" }
      - { name: "url", label: "Link", widget: "string", required: false }
      - { name: "dateTime", label: "Data", widget: "datetime" }
  - name: "news"
    label: "Notícias"
    folder: "src/data/news"
    create: true
    slug: "{{uuid}}"
    fields:
      - { name: "url", label: "Link", widget: "string" }
      - { name: "title", label: "Título", widget: "string" }
      - { name: "description", label: "Descrição", widget: "text", required: false }
      - { name: "dateTime", label: "Data", widget: "date" }
